spring:
  application:
    name: library-management

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: 6100

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true