spring:
  application:
    name: library-management

  profiles:
    active: dev

  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

admin:
  default-username: ${ADMIN_USERNAME}
  default-email: ${ADMIN_EMAIL}
  default-password: ${ADMIN_PASSWORD}

cache:
  book:
    ttl-minutes: 10
    max-size: 500

file:
  upload:
    dir: ${FILE_UPLOAD_DIR:uploads}
    allowed-extensions: ${FILE_ALLOWED_EXTENSIONS:jpg,jpeg,png,webp}
    max-size-bytes: ${FILE_MAX_SIZE_BYTES:5242880}